"""PotentialField -- gravitational potential computation and traffic light optimizer.

Reference implementation for the Janus traffic model (C-01, section 1.3).
This module computes the scalar gravitational potential field generated by
all vehicles on an arbitrary set of evaluation points (grid or otherwise).

Potential formula:
    Phi_i(r) = -sign(m_i) * G_s * |m_i| / r

where *r* is the Euclidean distance from vehicle *i* to the evaluation point,
clamped to a minimum ``r_min`` to prevent singularity.

Sign convention:
    - Positive mass (slow vehicle) -> Phi < 0 -> congestion well (attracting)
    - Negative mass (fast vehicle) -> Phi > 0 -> fluid hill (repelling)

Total potential at point (x, y):
    Phi(x, y) = sum_i  Phi_i(r_i)

The traffic light optimizer uses the potential field as a proxy for congestion
pressure at an intersection, sweeping green-phase durations to find the timing
that minimises total congestion cost.

Author: Agent #01 Python Scientific Developer
Date: 2026-03-22
"""

from __future__ import annotations

import numpy as np
import numpy.typing as npt

__all__ = [
    "compute_potential_field",
    "make_grid",
    "optimize_traffic_light",
]


def compute_potential_field(
    vehicle_positions: npt.NDArray[np.float64],
    vehicle_masses: npt.NDArray[np.float64],
    grid_centers: npt.NDArray[np.float64],
    G_s: float = 5.0,
    r_min: float = 5.0,
) -> npt.NDArray[np.float64]:
    """Compute the gravitational potential at each grid point.

    Parameters
    ----------
    vehicle_positions : ndarray, shape (N, 2), dtype float64
        (x, y) coordinates of each vehicle.
    vehicle_masses : ndarray, shape (N,), dtype float64
        Signed gravitational mass of each vehicle.
    grid_centers : ndarray, shape (M, 2), dtype float64
        (x, y) coordinates of the evaluation points.
    G_s : float, default 5.0
        Social gravitational constant (unified calibration).
    r_min : float, default 5.0
        Minimum distance (meters) to clamp the denominator and avoid
        singularity at r = 0.

    Returns
    -------
    ndarray, shape (M,), dtype float64
        Scalar potential Phi at each grid point.

    Notes
    -----
    Fully vectorized via broadcasting:

        displacements : (M, 1, 2) - (1, N, 2) -> (M, N, 2)
        distances     : (M, N)
        contributions : (M, N)
        potential     : (M,)  via sum over axis=1

    The potential contribution from vehicle *i* at evaluation point *p* is::

        Phi_i = -sign(m_i) * G_s * |m_i| / max(r_{pi}, r_min)

    All arithmetic is float64.
    """
    vehicle_positions = np.asarray(vehicle_positions, dtype=np.float64)
    vehicle_masses = np.asarray(vehicle_masses, dtype=np.float64)
    grid_centers = np.asarray(grid_centers, dtype=np.float64)

    n = len(vehicle_masses)
    m = len(grid_centers)

    # Handle empty vehicles: return zeros
    if n == 0:
        return np.zeros(m, dtype=np.float64)

    # Validate shapes
    if vehicle_positions.shape != (n, 2):
        raise ValueError(
            f"vehicle_positions shape {vehicle_positions.shape} incompatible "
            f"with {n} masses; expected ({n}, 2)"
        )
    if grid_centers.ndim != 2 or grid_centers.shape[1] != 2:
        raise ValueError(f"grid_centers must have shape (M, 2), got {grid_centers.shape}")

    # Broadcasting: (M, 1, 2) - (1, N, 2) -> (M, N, 2)
    diff = grid_centers[:, np.newaxis, :] - vehicle_positions[np.newaxis, :, :]  # (M, N, 2)

    # Euclidean distance: (M, N)
    dist = np.sqrt(np.sum(diff * diff, axis=2))

    # Clamp to r_min to avoid division by zero / singularity
    dist = np.maximum(dist, r_min)

    # Potential contributions: -sign(m_i) * G_s * |m_i| / r
    # Vectorized over both grid points (M) and vehicles (N)
    signs = np.sign(vehicle_masses)  # (N,)
    abs_masses = np.abs(vehicle_masses)  # (N,)

    # (M, N) = -(1, N) * G_s * (1, N) / (M, N)
    contributions = -signs[np.newaxis, :] * G_s * abs_masses[np.newaxis, :] / dist

    # Sum over all vehicles -> (M,)
    potential = np.sum(contributions, axis=1)

    return potential


def make_grid(
    x_min: float,
    y_min: float,
    x_max: float,
    y_max: float,
    resolution: float = 10.0,
) -> npt.NDArray[np.float64]:
    """Create a regular 2D grid of center points.

    Parameters
    ----------
    x_min, y_min : float
        Lower-left corner of the grid domain.
    x_max, y_max : float
        Upper-right corner of the grid domain.
    resolution : float, default 10.0
        Spacing between grid centers in both x and y (meters).

    Returns
    -------
    ndarray, shape (M, 2), dtype float64
        (x, y) coordinates of the M grid center points, ordered row-major
        (y varies slowest).

    Notes
    -----
    Grid points are placed at the centers of cells, starting at
    ``x_min + resolution/2`` and ending at or before ``x_max``.
    """
    half = resolution / 2.0
    xs = np.arange(x_min + half, x_max, resolution, dtype=np.float64)
    ys = np.arange(y_min + half, y_max, resolution, dtype=np.float64)

    # meshgrid with 'xy' indexing: xx varies along columns, yy along rows
    xx, yy = np.meshgrid(xs, ys, indexing="xy")

    # Flatten and stack: (M, 2)
    grid = np.column_stack([xx.ravel(), yy.ravel()])

    return grid


def optimize_traffic_light(
    vehicle_positions: npt.NDArray[np.float64],
    vehicle_masses: npt.NDArray[np.float64],
    intersection_pos: npt.NDArray[np.float64],
    radius: float = 200.0,
    G_s: float = 5.0,
    horizon_s: int = 120,
) -> dict:
    """Optimize traffic light timing using potential-field congestion proxy.

    Evaluates the gravitational potential at the intersection center for
    vehicles within the given radius, then sweeps green-phase durations
    to find the timing that minimises total congestion cost.

    The cost function for a given ``green_ns`` is::

        cost = |min(0, Phi)| * weight_ns + |min(0, Phi)| * weight_ew

    where the weights are proportional to the green time allocated to each
    phase (more green -> more throughput -> lower effective congestion).

    Parameters
    ----------
    vehicle_positions : ndarray, shape (N, 2), dtype float64
        (x, y) coordinates of each vehicle.
    vehicle_masses : ndarray, shape (N,), dtype float64
        Signed gravitational mass of each vehicle.
    intersection_pos : ndarray, shape (2,), dtype float64
        Center of the intersection.
    radius : float, default 200.0
        Only vehicles within this distance (meters) are considered.
    G_s : float, default 5.0
        Social gravitational constant (unified calibration).
    horizon_s : int, default 120
        Cycle length in seconds. ``green_ew = max(10, horizon_s - green_ns - 10)``,
        where 10 s is the all-red/amber clearance time.

    Returns
    -------
    dict
        ``{'green_ns': int, 'green_ew': int, 'cycle_s': int, 'phi_cost': float}``
        The optimal timing and corresponding congestion cost.

    Notes
    -----
    This is a simplified proxy optimizer. A full model would integrate the
    potential over the horizon with time-varying vehicle dynamics. Here we
    use the instantaneous potential as a stand-in, weighted by green-phase
    fractions.

    The method is fully vectorized internally (no Python loops over vehicles
    or grid points). The sweep over green timings is a small fixed-size loop
    (16 iterations) which is not a performance concern.
    """
    vehicle_positions = np.asarray(vehicle_positions, dtype=np.float64)
    vehicle_masses = np.asarray(vehicle_masses, dtype=np.float64)
    intersection_pos = np.asarray(intersection_pos, dtype=np.float64)

    # Select vehicles within radius
    if len(vehicle_masses) > 0:
        diff = vehicle_positions - intersection_pos[np.newaxis, :]  # (N, 2)
        dists = np.sqrt(np.sum(diff * diff, axis=1))  # (N,)
        mask = dists <= radius
        nearby_pos = vehicle_positions[mask]
        nearby_mass = vehicle_masses[mask]
    else:
        nearby_pos = np.empty((0, 2), dtype=np.float64)
        nearby_mass = np.empty((0,), dtype=np.float64)

    # Compute potential at intersection center
    eval_point = intersection_pos.reshape(1, 2)  # (1, 2) for compute_potential_field
    phi = compute_potential_field(nearby_pos, nearby_mass, eval_point, G_s=G_s)
    phi[0]  # scalar

    # Separate NS and EW contributions using directional decomposition
    # NS vehicles: |dy| > |dx| relative to intersection
    # EW vehicles: |dx| >= |dy| relative to intersection
    if len(nearby_mass) > 0:
        rel = nearby_pos - intersection_pos[np.newaxis, :]
        ns_mask = np.abs(rel[:, 1]) > np.abs(rel[:, 0])
        ew_mask = ~ns_mask

        phi_ns = compute_potential_field(
            nearby_pos[ns_mask], nearby_mass[ns_mask], eval_point, G_s=G_s
        )[0]
        phi_ew = compute_potential_field(
            nearby_pos[ew_mask], nearby_mass[ew_mask], eval_point, G_s=G_s
        )[0]
    else:
        phi_ns = 0.0
        phi_ew = 0.0

    # Congestion = absolute negative potential (wells only)
    congestion_ns = abs(min(0.0, float(phi_ns)))
    congestion_ew = abs(min(0.0, float(phi_ew)))

    clearance_s = 10  # all-red + amber clearance

    best_cost = np.inf
    best_green_ns = 15
    best_green_ew = 10

    # Sweep green_ns from 15 to 90 in steps of 5
    for green_ns in range(15, 91, 5):
        green_ew = max(10, horizon_s - green_ns - clearance_s)

        # Cost: congestion weighted inversely by green time fraction
        # More green time -> better throughput -> lower effective cost
        # Avoid division by zero: green times are always >= 10
        frac_ns = green_ns / horizon_s
        frac_ew = green_ew / horizon_s

        # Cost = congestion / fraction (higher fraction = lower cost)
        cost = congestion_ns / frac_ns + congestion_ew / frac_ew

        if cost < best_cost:
            best_cost = cost
            best_green_ns = green_ns
            best_green_ew = green_ew

    return {
        "green_ns": best_green_ns,
        "green_ew": best_green_ew,
        "cycle_s": horizon_s,
        "phi_cost": float(best_cost),
    }
